### ISSUE TITLE
Unable to see the addon after extracting

### ISSUE THREAD

**Issue by Songisamson** [LeftHandedGlove/WeaponSwingTimerAddon#4]
I download the file, extract to the wow classic interface folder and it doesnt show up, not sure what else to do, no other addon is having this issue

**Comment by Songisamson** [comment]
Figured it out, had to rename the extracted folder, was "WeaponSwingTimerAddon-master" showed up once it was set to "WeaponSwingTimer"

**Comment by LeftHandedGlove** [comment]
Yeah, I wish Blizzard would let you know that it couldn't load an addon because if illegal characters. It doesn't like '-' as you've found out.
