### ISSUE TITLE
Error spam whilst in duel with rogue 

### ISSUE THREAD

**Issue by towneh** [LeftHandedGlove/WeaponSwingTimerAddon#5]
Message: ...\AddOns\WeaponSwingTimer\WeaponSwingTimer_Target.lua:91: attempt to compare number with nil
Time: Tue Jun  4 01:15:35 2019
Count: 3149
Stack: ...\AddOns\WeaponSwingTimer\WeaponSwingTimer_Target.lua:91: attempt to compare number with nil
...\AddOns\WeaponSwingTimer\WeaponSwingTimer_Target.lua:91: in function `UpdateSwingTimer'
...ce\AddOns\WeaponSwingTimer\WeaponSwingTimer_Core.lua:56: in function <...ce\AddOns\WeaponSwingTimer\WeaponSwingTimer_Core.lua:54>
...ce\AddOns\WeaponSwingTimer\WeaponSwingTimer_Core.lua:81: in function <...ce\AddOns\WeaponSwingTimer\WeaponSwingTimer_Core.lua:80>

Locals: elapsed = 0.017000
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
addon_data = <table> {
 core = <table> {
 }
 player = <table> {
 }
 target = <table> {
 }
 utils = <table> {
 }
 config = <table> {
 }
}

**Comment by LeftHandedGlove** [comment]
I'm thinking this is an issue with having an old version. I put in a check there to see if the target has an offhand. If it keeps happening then let me know but I'm closing this unless it pops up again.
