### ISSUE TITLE
Swing timer bars mis-aligned when switching from 2H to 1H/Shield

### ISSUE THREAD

**Issue by towneh** [LeftHandedGlove/WeaponSwingTimerAddon#6]
https://www.youtube.com/watch?v=otJJBiM7AHE

**Comment by LeftHandedGlove** [comment]
That is really weird. It looks like it recognises the shield as an off-hand weapon for some reason. I made a change to update the player info in combat so maybe that will fix it. I'll see if I can recreate it. I'll see if I can fix it in version 3.2

**Comment by LeftHandedGlove** [comment]
It also looks like its an issue with the anchor.

**Comment by LeftHandedGlove** [comment]
I think I fixed it. Whenever the player would swap weapons it wouldnt reset the swing timer but it woul update the weapon speed so the timer would go into the negative which caused the text to go off the bar.

**Comment by LeftHandedGlove** [comment]
Closing the issue. The fix is in version 3.1 and in master.
