### ISSUE TITLE
LUA error at start.

### ISSUE THREAD

**Issue by Tga123** [LeftHandedGlove/WeaponSwingTimerAddon#7]
Date: 2019-08-27 14:50:18
ID: 1
Error occured in: Global
Count: 1
Message: ...\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua line 93:
   attempt to compare number with nil
Debug:
   [C]: ?
   ...\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:93: StartCastingSpell()
   ...\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:70:
      ...\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:66
   [C]: UseAction()
   ..\FrameXML\SecureTemplates.lua:338: handler()
   ..\FrameXML\SecureTemplates.lua:616: SecureActionButton_OnClick()
   ..\FrameXML\ActionButton.lua:100:
      ..\FrameXML\ActionButton.lua:94
   ..\FrameXML\ActionButton.lua:136: ActionButtonDown()
   [string "ACTIONBUTTON2"]:2:
      [string "ACTIONBUTTON2"]:1
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11302
  Ace3, v
  AdvancedInterfaceOptions, v1.3.0
  AtlasLootClassic, vv1.1.6-beta
  Auctionator, v8.1.0
  BagFreeSpaceCounter, v1.0.2
  BlizzMove, v1.9
  Chatter, v1.5.8
  ClassicAuraDurations, v
  ClassicAutoDismount, v1.01
  ClassicLFG, v1.0.0
  ClassicSpellActivations, v
  ClassicSpellRanks, v1.1
  ClassicThreatMeter, v1.0
  DBMCore, v1.13.2-6-g93d7fe2
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  FieldGuide, vv1.3-release
  idTip, v8.2.1
  Informant, v8.2.6374 (SwimmingSeadragon)
  LibClassicItemSets10, v1.0.0
  Mapster, v1.8.4
  MaxCam, vv2.4.0-classic
  ModernQuestWatch, v1.0.8
  OmniCC, v8.1.1
  Quartz, v3.5.0-2-g342c091
  QuestFrameFixer, v1.1.1
  Questie, v4.0.10 BETA
  RealMobHealth, v2.3
  RepHelperClassic, v1.13.2.2-release
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  StandUp, v1.0.0
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TrackResources, v0.7
  TradeSkillMaster, vv4.8.2
  VuhDo, v3.102
  VuhDoOptions, v3.102
  WeaponSwingTimer, v4.0.1
  BlizRuntimeLib_ruRU v1.13.2.11302 <none>
  (ck=438)

**Comment by LeftHandedGlove** [comment]
Do you know which spell caused this? I'll add a check and push out an update soon

**Comment by LeftHandedGlove** [comment]
I haven't heard anything but I added something that should remedy this. I'm going with no news is good news and closing this.
