### ISSUE TITLE
Warriors Heroic Strike does not trigger swing timer

### ISSUE THREAD

**Issue by 3axap4eHko** [LeftHandedGlove/WeaponSwingTimerAddon#8]

**Comment by LeftHandedGlove** [comment]
Which client language are you using? At the moment it only works on the English client. I'm currently working on making it work everywhere .

**Comment by 3axap4eHko** [comment]
@LeftHandedGlove I'm using Russian client

**Comment by LeftHandedGlove** [comment]
This should now be fixed with version 4.1.0.
When you get the chance, download it and let me know if you still see the issue.
Thank you
