### ISSUE TITLE
Addon Integration

### ISSUE THREAD

**Issue by illion20** [LeftHandedGlove/WeaponSwingTimerAddon#9]
How can another addon register to the swing timer reset?
Is it possible to use this as an API or just dependency to get the swing timer resets?

**Comment by LeftHandedGlove** [comment]
I'm not 100% certain how to hook together add-ons or develop APIs for add-ons.
That said, as long as you change the enabled setting on all the bars to false, the background logic should still run but the visuals will be hidden.

**Comment by illion20** [comment]
I realized the swing reset was actually just SWING_DAMAGE MISS SPELL events so I incorporated that.

thank you
